### ISSUE TITLE
[FEATURE] Streaming de réponse

### ISSUE THREAD

**Issue by JosselinTILLAY** [deeplore-ai/deeplore#3]
Plutôt que d'attendre la réponse entière pour l'afficher ensuite ligne par ligne, il faudrait utiliser le straming de réponse dont on a parlé pendant le hackathon

**Comment by JosselinTD** [comment]
J'ai essayé. Dans le cadre de gemini (qui est le modèle qu'on utilise en ce moment), le résultat n'arrive pas plus vite, et ça complexifie beaucoup le code
