### ISSUE TITLE
[BUG] Fuite mémoire backend

### ISSUE THREAD

**Issue by CartierPierre** [deeplore-ai/deeplore#7]
Corriger rapidement le problème du backend Fast API qui instancie des vector stores sans jamais les vider

**Comment by thomasBontempsFr** [comment]
Il faut qu'à la fin de session d'un utilisateur, une requête api se fasse pour surprimer tous les fichiers créés par la session de jeu.

@CartierPierre Je vois qu'une variable Vecteur est créée pour chaque utilisateur. Cette variable est-elle stockée ? 

Si réalisable directement dans le server, réaliser lors de la compilation du code dans le serveur le Vecteur sur tous les documents. 
Load cette variable et l'utiliser dans le fichier python LangChain

**Comment by thomasBontempsFr** [comment]
Pour stocker le vecteur, j'ai trouvé ça : 
```
vector = FAISS.from_documents(docs, embeddings)
vector.save_local("faiss_index")
vector = FAISS.load_local("faiss_index", embeddings)
```

Cela enlèvera le temps d'execution du vecteur mais obligé de le charger pour chaque session. Autrement, faut qu'il le load sur le chache de leur propre machine.

**Comment by thomasBontempsFr** [comment]
La fuite a été réglée il me semble ?

**Comment by JosselinTD** [comment]
Je n'ai pas reconstaté de fuite mémoire. Avec toutes les modifications, le problème a du être réglé.

J'ai aussi implémenté le save_local, ça accélère le redémarrage serveur pendant le dev
